name: geo_reminder
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  geolocator: ^13.0.1
  flutter_local_notifications: ^17.2.2

  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
